name: timeline_master
description: Displays customizable timeline of widgets
version: 0.0.5
author: Furkan Tektas <tektasfurkan@gmail.com>
homepage: https://github.com/furkantektas/timeline_list


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter.
  timeline_list: ^0.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
