name: timeline_master

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter.
  #timeline_list: ^0.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
